### PR TITLE
systemd: use --ignition-url in service wrapper

### PR DESCRIPTION
**Pull request by bgilbert**
We no longer need to run curl by hand.

cc @jlebon

### CODE REVIEW

**Comment by lucab** [comment]
Wrt. retries, we do have some silly `retry` [module](https://github.com/coreos/afterburn/blob/master/src/retry/mod.rs) in Afterburn, which isn't particularly good and I'd be happy to drop in favor of a better crate. Honk if you have on in sight which is good enough to consolidate on.

**Comment by bgilbert** [comment]
Filed https://github.com/coreos/coreos-installer/issues/283 for HTTP retries.

**Comment by bgilbert** [comment]
Rebased.

**Comment by bgilbert** [comment]
CI noticed that we need to pass `--insecure-ignition`.  Updated.

**Pull request merged**
