### PR TITLE
rdcore/kargs: add --should-exist and --should-not-exist

### PR DESCRIPTION
**Pull request by jlebon**
See individual commit messages.

For https://github.com/coreos/ignition/issues/1168.

Requires: https://github.com/coreos/coreos-installer/pull/497

### CODE REVIEW

**Comment by arithx** [comment]
Hmm, WDYT about adding an option or default behavior that optionally would either output to a file or to stdout if any kargs were added/removed? That way we could avoid reboots if kargs were requested but no changes were actually needed?

**Comment by bgilbert** [comment]
Are we trying to avoid adding an ignition-kargs wrapper script around this subcommand?  Could a script capture kargs before and after, and do a comparison?

LGTM otherwise.

**Comment by arithx** [comment]
> Are we trying to avoid adding an ignition-kargs wrapper script around this subcommand? Could a script capture kargs before and after, and do a comparison?

We'd need one anyways because we need to mount `/boot` & pass in the `boot-mount` to `rdcore`. I was mostly suggesting it to avoid re-doing the check in bash when we already know that information in the rust code.

**Comment by jlebon** [comment]
Rebased and added `--touch-if-changed` in a separate commit!

As noted in the commit message there, this does add a new dep. If we're strongly opposed, I can add a wrapper for `utimensat` and drop the dep.

**Comment by jlebon** [comment]
OK, now changed to use `--create-if-changed` and dropped the dep! This should be good for a final review.

**Review by bgilbert — APPROVED** [review]

**Pull request merged**
