### PR TITLE
build-sys: Use new `tier = 2` for cargo-vendor-filterer

### PR DESCRIPTION
**Pull request by cgwalters**
This fixes the problem described in the comment.

### CODE REVIEW

**Comment by cgwalters** [comment]
see also e.g.
- https://github.com/coreos/rpm-ostree/pull/4429
- https://github.com/containers/bootc/pull/104

**Comment by bgilbert** [comment]
Since this widens the set of platforms we're including, it could conceivably change the contents of the vendor tarball.  Does it?  If so, we should probably release-note the change to vendored platforms under "packaging changes".

Also, it looks like there are a few other packages that will need updates.  Could you do those as well?
- [ ] afterburn
- [ ] bootupd
- [ ] ssh-key-dir
- [ ] zincati

**Comment by cgwalters** [comment]
> Since this widens the set of platforms we're including, it could conceivably change the contents of the vendor tarball. Does it?

Just verified that there are no changes to the vendored crate set.  It'd be surprising if there were - last I dug at this I didn't find any architecture-dependent crates, just platform dependent.

**Comment by bgilbert** [comment]
Okay, cool.  This LGTM; leaving open so we don't forget to update the other projects in https://github.com/coreos/coreos-installer/pull/1193#issuecomment-1560223004.

**Comment by bgilbert** [comment]
Thanks for doing the other PRs.  Once you get the Zincati one posted, I'll approve this.

**Pull request merged**
