### PR TITLE
cargo: refresh lockfile

### PR DESCRIPTION
**Pull request by bgilbert**
gptman and mbrman both changed their error libraries.

@nikita-dubrovskii, could you check this on s390x?

### CODE REVIEW

**Review by sohankunkerkar — COMMENTED** [review]
This change LGTM
Would ask @nikita-dubrovskii to approve this change based on the outcome on s390x

**Comment by bgilbert** [comment]
gptman updated in https://github.com/coreos/coreos-installer/pull/494 and mbrman updated in https://github.com/coreos/coreos-installer/pull/492.  Converting this to just a lockfile refresh.

**Comment by bgilbert** [comment]
libc 0.2.90 breaks openat; https://github.com/tailhook/openat/issues/35.

**Comment by bgilbert** [comment]
The metal4k test is consistently timing out in CI.  From the logs, it appears that c-i is still writing to disk when killed, and the same `testiso` command succeeds when run against a local build.  So I'm thinking that one of the dependency bumps is accentuating #184.

**Review by arithx — APPROVED** [review]

**Comment by nikita-dubrovskii** [comment]
Checked with custom RHCOS-48.84, works fine.
LGTM

**Comment by bgilbert** [comment]
This iteration now pulls in dependencies that are incompatible with our MSRV.  I'll just close this out for now.

**Pull request closed without merging**
