### PR TITLE
signing-keys: add Fedora 36 key

### PR DESCRIPTION
**Pull request by dustymabe**
We have a rawhide stream now and rawhide just switched to F36.

### CODE REVIEW

**Review by cgwalters — APPROVED** [review]

**Comment by bgilbert** [comment]
Historically we've dropped the old key at the same time.  It seems like the F33 key can go now.

**Comment by dustymabe** [comment]
> Historically we've dropped the old key at the same time. It seems like the F33 key can go now.

I hesitated. This isn't part of our normal transition (i.e. traditionally we did this as part of the transition of `next`/`next-devel`). With the rawhide stream we're shifting things forward a bit and I wasn't sure if we should also more aggressively trim the old key.

**Comment by bgilbert** [comment]
We don't support non-current releases, and `stable` switched to F34 three months ago, so I think it's fine to drop.  The rebase checklist doesn't mention dropping the old key (maybe it should?) so there's a risk we'll forget.

**Comment by dustymabe** [comment]
+1 - will open a PR

**Comment by dustymabe** [comment]
> +1 - will open a PR

https://github.com/coreos/coreos-installer/pull/600

**Comment by bgilbert** [comment]
Rebase checklist update in https://github.com/coreos/fedora-coreos-tracker/pull/930.

**Pull request merged**
