### PR TITLE
github/workflows: add Rust testing

### PR DESCRIPTION
**Pull request by lucab**
This adds a new workflow on GitHub with a few jobs for Rust testing.

### CODE REVIEW

**Comment by lucab** [comment]
Hmm, apparently this now fails https://github.com/lucab/coreos-installer/runs/1454047097?check_suite_focus=true

**Comment by lucab** [comment]
This is green on my fork: https://github.com/lucab/coreos-installer/actions/runs/383451721

**Review by jlebon — APPROVED** [review]
Should this PR also be removing `.travis.yml` ?

**Comment by lucab** [comment]
@jlebon possibly later? The travis jobs where also doing docker and s390x.

**Pull request merged**
